#!/usr/bin/env bash
#
#set -x
#############################
dict=/usr/share/dict/words
l=16
n=10
#############################
squeeze () {
	if [[ $words == true ]]; then
		tr '\n' ' '
	else
		tr -d '\n'
	fi
}
randomize () {
	local input=$1
	local length=${#input}
	local index=0
	local char
	local string
	while [[ $index -lt $length ]]; do
		char=${input:$index:1}
		if (( (RANDOM%10) < 3 )); then
			case $char in
				a)	char='@';;
				e)	char=3;;
				i)	char='!';;
				l)	char=1;;
				o)	char=0;;
				s)	char='$';;
				t)	char=7;;
				z)	char=2;;
				*)	char=${char^};;
			esac
		fi
		string="${string}${char}"
		((index++))
	done
	echo "$string"
}
r_sum () {
	local total=$1
	local remain=$total
	local temp
	local arr=()
	until (( $remain == 0 )); do
		if (( $remain <= 3 )); then
			arr+=( "$remain" )
			break
		fi
		temp=$(( RANDOM % (remain-2) + 1 ))
		((temp > 24)) && temp=$((RANDOM%24 + 1 ))
		[[ $temp -le 1 ]] && continue
		(( remain -= temp ))
		arr+=( "$temp" )
	done
	echo "${arr[@]}" | tr ' ' '\n' | sort -R | tr '\n' ' '
}
gen_pass () {
	{
	for l; do
		if [[ $complex == true ]]; then
			randomize $(awk -v l="$l" 'length == l' "$dict" | sort -R | tail -1)
		else
			awk -v l="$l" 'length == l' "$dict" | sort -R | tail -1
		fi
	done 
	}	| squeeze
	echo
}
#############################
while getopts l:n:cw opt; do
	case $opt in
		l)	l=$OPTARG;;
		n)	n=$OPTARG;;
		c)	complex=true;;
		w)	words=true;;
		*)	echo "ERROR: Unknown argument: $opt" >&2; exit 1;;
	esac
done
#############################
for ((i=0;i<n;i++)); do
	gen_pass $(r_sum "$l")
done
